import { Geist_Mono, Glory, Montserrat } from "next/font/google";
import "./globals.css";
import { NavProvider } from "@/context/NavContext";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const glory = Glory({
  variable: "--font-glory",
  subsets: ["latin"], // FIXED
  weight: "400",
});

const montserrat = Montserrat({
  variable: "--font-montserrat", // FIXED
  subsets: ["latin"], // FIXED
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/your-kit-id.css" />
      </head>

      <body
        className={`${geistMono.variable} ${glory.variable} ${montserrat.variable}`}
      >
        <NavProvider>{children}</NavProvider>
      </body>
    </html>
  );
}
