import { Geist, Geist_Mono, Glory } from "next/font/google";
import "./globals.css";
import { NavProvider } from "@/context/NavContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const glory = Glory({
  variable: "--font-glory-sans",
  subsets: ["sans-serif"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/your-kit-id.css" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${glory.variable}`}
      >
        <NavProvider>{children}</NavProvider>
      </body>
    </html>
  );
}
